### ISSUE TITLE
question scripts

### ISSUE THREAD

**Issue by Zarkness2** [W4545/ScriptExecutor#1]
I have a doubt with the plugin could I create for example a /fly command or more complex things? if so how would it be?

**Comment by W4545** [comment]
This project is for running shell scripts on the host system of the minecraft server from a command in the game, not for creating custom commands within minecraft.

Common examples of how I've seen this project used is on hosted minecraft servers where you don't have shell access, or in situations where minecraft server owners want to allow server admins the ability to do certain actions on the server without actually giving them shell access, like backing up config files, installing plugin updates, starting or stopping databases, etc.

**Comment by Zarkness2** [comment]
ok, thanks a lot, looks quite interesting, maybe I can think of something for my configurators and admins.
